import { useState } from 'react';
import {
  Button,
  FeatureCard,
  TestimonialCard,
  PricingCard,
  Navbar,
  Modal,
  Input,
  Checkbox,
  Select,
  Textarea,
  LoginForm,
  SignupForm,
  ContactForm
} from './components';
import './App.css';

function App() {
  const [showLogin, setShowLogin] = useState(false);
  const [showSignup, setShowSignup] = useState(false);
  const [showCustomModal, setShowCustomModal] = useState(false);
  const [expandedCard, setExpandedCard] = useState(null);

  const navLinks = [
    { label: 'Features', href: '#features' },
    { label: 'Testimonials', href: '#testimonials' },
    { label: 'Pricing', href: '#pricing' },
    { label: 'Contact', href: '#contact' }
  ];

  const navActions = [
    { label: 'Log In', variant: 'outline', onClick: () => setShowLogin(true) },
    { label: 'Get Started', variant: 'primary', onClick: () => setShowSignup(true) }
  ];

  const features = [
    { icon: 'feature-icon-1', title: 'AI Study Plans', desc: 'Get personalized study schedules generated by AI.' },
    { icon: 'feature-icon-2', title: 'Smart Pomodoro', desc: 'Customizable focus timer with intelligent breaks.' },
    { icon: 'feature-icon-3', title: 'Progress Analytics', desc: 'Track your study habits with visual insights.' },
    { icon: 'feature-icon-4', title: 'Task Management', desc: 'Organize assignments with smart priority sorting.' },
    { icon: 'feature-icon-5', title: 'Collaboration', desc: 'Share notes and collaborate with classmates.' },
    { icon: 'feature-icon-6', title: 'Focus Mode', desc: 'Block distractions and enter deep work mode.' }
  ];

  const testimonials = [
    { rating: 5, quote: 'StudyFlow completely transformed how I approach my coursework!', author: 'Sarah Johnson', role: 'Computer Science, MIT', initials: 'SJ' },
    { rating: 5, quote: 'The Pomodoro timer and focus mode are game-changers!', author: 'Michael Chen', role: 'Engineering, Stanford', initials: 'MC' },
    { rating: 5, quote: 'I went from struggling to being the most organized in my group.', author: 'Emma Patel', role: 'Biology, UCLA', initials: 'EP' }
  ];

  const pricingPlans = [
    { name: 'Free', desc: 'Perfect for getting started', price: '0', features: [{text: 'Basic task management'}, {text: '3 study plans/month'}, {text: 'Pomodoro timer'}, {text: 'Basic analytics'}, {included: false, text: 'AI recommendations'}, {included: false, text: 'Collaboration tools'}] },
    { name: 'Pro', desc: 'For serious students', price: '9', popular: true, features: [{text: 'Unlimited task management'}, {text: 'Unlimited AI study plans'}, {text: 'Smart Pomodoro with stats'}, {text: 'Advanced analytics'}, {text: 'AI recommendations'}, {text: 'Study groups (up to 5)'}, {included: false, text: 'Priority support'}] },
    { name: 'Team', desc: 'For study groups & tutors', price: '19', features: [{text: 'Everything in Pro'}, {text: 'Unlimited study groups'}, {text: 'Shared calendars'}, {text: 'Admin dashboard'}, {text: 'Team analytics'}, {text: 'Collaboration tools'}, {text: 'Priority support'}] }
  ];

  const handleLogin = (data) => {
    console.log('Login:', data);
    setShowLogin(false);
    alert('Login successful! Welcome back.');
  };

  const handleSignup = (data) => {
    console.log('Signup:', data);
    setShowSignup(false);
    alert(`Welcome, ${data.firstName}! Account created successfully.`);
  };

  const handleContact = (data) => {
    console.log('Contact:', data);
    alert('Message sent! We will get back to you soon.');
  };

  return (
    <div className="sf-demo">
      <Navbar links={navLinks} actions={navActions} />

      {/* Hero Section */}
      <section className="sf-hero">
        <div className="sf-hero__content">
          <h1 className="sf-hero__title">
            StudyFlow <span>Component Library</span>
          </h1>
          <p className="sf-hero__desc">
            A reusable, modular component library for building modern study productivity applications.
          </p>
          <div className="sf-hero__actions">
            <Button variant="primary" size="lg" onClick={() => setShowSignup(true)}>Get Started</Button>
            <Button variant="secondary" size="lg" onClick={() => setShowLogin(true)}>Log In</Button>
          </div>
        </div>
      </section>

      {/* Buttons Section */}
      <section className="sf-section" id="buttons">
        <h2 className="sf-section__title">Buttons</h2>
        <div className="sf-section__content">
          <div className="sf-demo-row">
            <span className="sf-demo-label">Variants</span>
            <Button>Primary</Button>
            <Button variant="secondary">Secondary</Button>
            <Button variant="outline">Outline</Button>
            <Button variant="white">White</Button>
            <Button variant="danger">Danger</Button>
          </div>
          <div className="sf-demo-row">
            <span className="sf-demo-label">Sizes</span>
            <Button size="sm">Small</Button>
            <Button size="md">Medium</Button>
            <Button size="lg">Large</Button>
          </div>
          <div className="sf-demo-row">
            <span className="sf-demo-label">States</span>
            <Button>Normal</Button>
            <Button disabled>Disabled</Button>
            <Button loading>Loading</Button>
            <Button fullWidth>Full Width</Button>
          </div>
        </div>
      </section>

      {/* Feature Cards Section */}
      <section className="sf-section" id="features">
        <h2 className="sf-section__title">Feature Cards</h2>
        <div className="sf-section__content">
          <div className="sf-cards-grid">
            {features.map((f, i) => (
              <FeatureCard
                key={i}
                icon={f.icon}
                title={f.title}
                description={f.desc}
                onClick={() => setExpandedCard(expandedCard === i ? null : i)}
                expanded={expandedCard === i}
              >
                <p>This is expanded content showing more details about {f.title}. You can add any additional content here.</p>
              </FeatureCard>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="sf-section" id="testimonials">
        <h2 className="sf-section__title">Testimonial Cards</h2>
        <div className="sf-section__content">
          <div className="sf-cards-grid">
            {testimonials.map((t, i) => (
              <TestimonialCard
                key={i}
                rating={t.rating}
                quote={t.quote}
                authorName={t.author}
                authorRole={t.role}
                authorInitials={t.initials}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="sf-section" id="pricing">
        <h2 className="sf-section__title">Pricing Cards</h2>
        <div className="sf-section__content">
          <div className="sf-cards-grid">
            {pricingPlans.map((p, i) => (
              <PricingCard
                key={i}
                planName={p.name}
                description={p.desc}
                price={p.price}
                period="/month"
                popular={p.popular}
                features={p.features}
                onAction={() => alert(`Selected ${p.name} plan`)}
                actionLabel={p.popular ? 'Start Free Trial' : 'Get Started'}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Forms Section */}
      <section className="sf-section" id="forms">
        <h2 className="sf-section__title">Form Components</h2>
        <div className="sf-section__content">
          <div className="sf-forms-demo">
            <div className="sf-form-demo-box">
              <h3>Input Fields</h3>
              <div className="sf-form-demo-fields">
                <Input label="Email" type="email" placeholder="you@example.com" />
                <Input label="Password" type="password" placeholder="Enter password" error="Incorrect password" />
                <Input label="Disabled" disabled value="Cannot edit" />
              </div>
            </div>
            <div className="sf-form-demo-box">
              <h3>Checkbox & Select</h3>
              <div className="sf-form-demo-fields">
                <Checkbox label="I agree to the terms" />
                <Checkbox label="Remember me" checked />
                <Checkbox label="Disabled" disabled />
                <Select
                  label="Select Option"
                  options={[
                    { value: '1', label: 'Option 1' },
                    { value: '2', label: 'Option 2' },
                    { value: '3', label: 'Option 3' }
                  ]}
                  placeholder="Choose..."
                />
              </div>
            </div>
            <div className="sf-form-demo-box" id="contact">
              <h3>Contact Form</h3>
              <ContactForm onSubmit={handleContact} />
            </div>
          </div>
        </div>
      </section>

      {/* Modal Demo */}
      <section className="sf-section">
        <h2 className="sf-section__title">Modals</h2>
        <div className="sf-section__content">
          <div className="sf-demo-row">
            <Button onClick={() => setShowLogin(true)}>Open Login Modal</Button>
            <Button onClick={() => setShowSignup(true)}>Open Signup Modal</Button>
            <Button onClick={() => setShowCustomModal(true)}>Open Custom Modal</Button>
          </div>
        </div>
      </section>

      <footer className="sf-footer">
        <p>StudyFlow Component Library &copy; 2026</p>
      </footer>

      {/* Modals */}
      <LoginForm isOpen={showLogin} onClose={() => setShowLogin(false)} onSubmit={handleLogin} />
      <SignupForm isOpen={showSignup} onClose={() => setShowSignup(false)} onSubmit={handleSignup} />
      <Modal isOpen={showCustomModal} onClose={() => setShowCustomModal(false)}>
        <h2 style={{ margin: 0 }}>Custom Modal</h2>
        <p>This modal is built using the reusable Modal component. You can put any content here.</p>
        <Button onClick={() => setShowCustomModal(false)}>Close</Button>
      </Modal>
    </div>
  );
}

export default App;